-- AlterTable
ALTER TABLE `INC_PURCHASES` ADD COLUMN `course_id` INTEGER NULL;

-- AddForeignKey
ALTER TABLE `INC_PURCHASES` ADD CONSTRAINT `INC_PURCHASES_course_id_fkey` FOREIGN KEY (`course_id`) REFERENCES `INC_COURSES`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
