-- CreateTable
CREATE TABLE `CURSED_STUDENTS` (
    `id` VARCHAR(191) NOT NULL,
    `student_name` VARCHAR(191) NOT NULL,
    `student_email` VARCHAR(191) NOT NULL,
    `student_password` VARCHAR(191) NOT NULL,
    `student_birth` DATETIME(3) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CURSED_COURSES` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `course_name` VARCHAR(191) NOT NULL,
    `course_price` DECIMAL(10, 2) NOT NULL,
    `course_description` VARCHAR(191) NOT NULL,
    `course_offer` INTEGER NULL,
    `course_time` INTEGER NULL,
    `teacher_id` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CURSED_CLASSES` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `class_name` VARCHAR(191) NOT NULL,
    `class_description` VARCHAR(191) NOT NULL,
    `class_time` INTEGER NULL,
    `class_video` VARCHAR(191) NOT NULL,
    `course_id` INTEGER NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CURSED_TEACHERS` (
    `id` VARCHAR(191) NOT NULL,
    `teacher_name` VARCHAR(191) NOT NULL,
    `teacher_email` VARCHAR(191) NOT NULL,
    `teacher_password` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CURSED_BOOKCASES` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `course_id` INTEGER NOT NULL,
    `student_id` VARCHAR(191) NOT NULL,
    `purchase_id` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CURSED_PURCHASES` (
    `id` VARCHAR(191) NOT NULL,
    `purchase_method` VARCHAR(191) NOT NULL,
    `purchase_price` DECIMAL(10, 2) NOT NULL,
    `purchade_status` INTEGER NOT NULL DEFAULT 0,
    `course_id` INTEGER NOT NULL,
    `student_id` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `CURSED_COURSES` ADD CONSTRAINT `CURSED_COURSES_teacher_id_fkey` FOREIGN KEY (`teacher_id`) REFERENCES `CURSED_TEACHERS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CURSED_CLASSES` ADD CONSTRAINT `CURSED_CLASSES_course_id_fkey` FOREIGN KEY (`course_id`) REFERENCES `CURSED_COURSES`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CURSED_BOOKCASES` ADD CONSTRAINT `CURSED_BOOKCASES_course_id_fkey` FOREIGN KEY (`course_id`) REFERENCES `CURSED_COURSES`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CURSED_BOOKCASES` ADD CONSTRAINT `CURSED_BOOKCASES_student_id_fkey` FOREIGN KEY (`student_id`) REFERENCES `CURSED_STUDENTS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CURSED_BOOKCASES` ADD CONSTRAINT `CURSED_BOOKCASES_purchase_id_fkey` FOREIGN KEY (`purchase_id`) REFERENCES `CURSED_PURCHASES`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CURSED_PURCHASES` ADD CONSTRAINT `CURSED_PURCHASES_course_id_fkey` FOREIGN KEY (`course_id`) REFERENCES `CURSED_COURSES`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CURSED_PURCHASES` ADD CONSTRAINT `CURSED_PURCHASES_student_id_fkey` FOREIGN KEY (`student_id`) REFERENCES `CURSED_STUDENTS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
